# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Peter Blouw
tagline:          ''
description:      ''
url:              http://peterblouw.org
baseurl:          ''

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

# paginate:         5
gems:
        # [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
